# language: generic
sudo: required  # we need super user permissions to make use of docker
services:
  - docker

before_install:   # it is going to have a series of different commands that get executed before our tests are ran.
  - docker build -t sw3196/docker-react -f Dockerfile.dev .  # cannot forget the last dot!!!

script: # the script section is supposed to contain all the different commands that need to be executed to
        # run our test suite.
  - docker run -e CI=true sw3196/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-381289070463"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"