version: '3'
services:
  web:
    build: 
      context: .    # specify where we want all the files and folders 
                    # for this image to be pulled from.
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  test:   # the second container is responsible for running our tests
          # and rerunning any time that any file inside of our volumes change
    build:
      context: .
      dockerfile: Dockerfile.dev
    # test 不需要 ports
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
